+++
date = "2017-11-20"
lastmod = "2017-11-20"
title = "RuboCop で2回目以降にエラーが出る"
slug = "rubocop-error"
tags = [
  "ruby",
  "ruboCop"
]
thumbnail = "images/logo_ruby.png"
toc = true
draft = false
+++

RuboCop で、最初の実行では上手く行ったのに、2回目以降エラーになってしまうことがありました。  
その時のエラーはこちら。

```
$ rubocop

invalid byte sequence in UTF-8
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/parser-2.4.0.0/lib/parser/source/buffer.rb:164:in `source='
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/cached_data.rb:47:in `deserialize_offenses'
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/cached_data.rb:13:in `from_json'
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/result_cache.rb:94:in `load'
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/runner.rb:119:in `file_offense_cache'
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/runner.rb:109:in `file_offenses'
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/runner.rb:100:in `process_file'
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/runner.rb:75:in `each'
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/runner.rb:75:in `reduce'
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/runner.rb:75:in `each_inspected_file'
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/runner.rb:67:in `inspect_files'
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/runner.rb:39:in `run'
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/cli.rb:87:in `execute_runner'
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/lib/rubocop/cli.rb:32:in `run'
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rubocop-0.51.0/bin/rubocop:13:in `block in <top (required)>'
/Users/<ユーザ名>/.rbenv/versions/2.3.5/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
```

最初は成功したのに、おかしい...と思って、キャッシュを無効にして実行したら、エラーは出なくなりました。


```
$ rubocop --cache false
```

キャッシュを有効にしたままエラーが出なくする方法は未調査です。  
RuboCopのキャッシュについては公式サイトの[このページ](http://rubocop.readthedocs.io/en/latest/caching/)に説明があります。

以上です。
